name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install server dependencies
      run: npm install
      working-directory: ./server

    - name: Install client dependencies
      run: npm install
      working-directory: ./client

    - name: Run application
      env:
        DATABASE: ${{ secrets.DATABASE }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: npm start
      working-directory: ./server
