env:
  DATABASE: ${{ secrets.DATABASE }}
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
